name: Check & Busted

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v5

      - uses: leafo/gh-actions-luarocks@v2

      - name: build
        run: luarocks install busted
          && luarocks install luacheck
          && luarocks install luacov
          && luarocks install luacov-coveralls

      - name: luacheck
        run: luacheck .

      - name: busted
        run: busted -R Test/Lib --verbose --coverage
