name: Busted

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v5

      - uses: leafo/gh-actions-luarocks@v2

      - name: build
        run: luarocks install busted

      - name: test
        run: busted -o utfTerminal -p Test -R Test/
